# Generated by Django 5.2.4 on 2025-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
