# Generated by Django 5.2.4 on 2025-07-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_patient_gender_alter_test_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
